[package]
name = "testcrate"
version = "0.1.0"
authors = ["Aleksandr Orlenko <zxteam@protonmail.com>"]

[features]
default = ["picolua54"]
picolua54 = []

[build-dependencies]
lua-src = { path = ".." }
